### ISSUE TITLE
［Function request］I want you to support Japanese.

### ISSUE THREAD

**Issue by jjtpjjj** [cranci1/Ryu#12]
I have two things I want.
The first is to support Japanese audio.
The second is to be able to erase the subtitles.

**Comment by cranci1** [comment]
Do you know any Japanese sites? (don't share the full url)

**Comment by jjtpjjj** [comment]
I don't know about the Japanese site.

On the hianime site (browser), you can set it to turn off the Japanese audio and subtitles.
![Uploading IMG_0944~2.PNG…]()

Even if you change the source to HiAnime from the Ryu app, the audio won't be in Japanese depending on the anime. The same goes for the subtitles.

**Comment by jjtpjjj** [comment]
There was no option to hide the subtitles.
But there were no subtitles.
![IMG_0945~2](https://github.com/user-attachments/assets/6442940b-2911-48ab-bc8d-facc64a11507)

My request for Japanese support has been fulfilled.
Thank you!
