### ISSUE TITLE
［Bug？］The behavior of displaying subtitles is different between TestFlight and ipa.

### ISSUE THREAD

**Issue by jjtpjjj** [cranci1/Ryu#14]
TestFlight and ipa have different behaviors for displaying subtitles.

[What's the difference?]
I set the same settings for TestFlight and ipa, but English subtitles are displayed.

TestFlight displays English subtitles.

ipa does not display English subtitles.

[Procedure for reproducing]
1. Open the "Ryu" app.
2. Open "Settings".
3. Change "Selected Source" to HiAnime.
4. Tap "Sources Preferences".
5. Change "Preferred Audio" to sub.
6. Play the anime.
7. Check if there are subtitles.

I'm not sure if this is related, but in the case of TestFlight, the "Subtitles Language" item only has English.
![IMG_0950](https://github.com/user-attachments/assets/300236d3-63f4-4d17-84d2-b23a3c1c843d)

ipa has six options.
![IMG_0945 (1)](https://github.com/user-attachments/assets/caf07e7f-c155-495d-aed1-80db2de1db4e)

**Comment by cranci1** [comment]
yes, that's because you need to use the "nightly ipa": you can get it here:
https://nightly.link/cranci1/Ryu/workflows/build/main/Ryu-IPA

**Comment by jjtpjjj** [comment]
I used https://nightly.link/cranci1/Ryu/workflows/build/main/Ryu-IPA.zip
and the subtitles are displayed.

However, when I use Release 1.0.3, the subtitles are not displayed.

**Comment by jjtpjjj** [comment]
I was wrong.

I learned that when playing anime, you can turn off the subtitles by clicking the gear icon that appears in the bottom right.
