### ISSUE TITLE
[BUG] Custom Player anime image issue

### ISSUE THREAD

**Issue by jjtpjjj** [cranci1/Ryu#16]
**Describe the bug**
The animated images are not displayed.

**To Reproduce**
1) Settings>Selected Source>HiAnime
2) Play the anime.
3) Stop watching anime. (Otherwise, close the Ryu app itself.)
4) Play the anime from Continue Watching.
5) The animated images are not displayed.

**Expected behavior**
Anime images will be displayed even when you select Continue Watching.

**Screenshots**
Images without anime images shown.
![IMG_0986~2](https://github.com/user-attachments/assets/57c76444-8b10-489b-8cda-8b6e9ba4f1ae)

An image showing an anime image.
![IMG_0987~2](https://github.com/user-attachments/assets/ec255e78-81e4-4cda-b7e3-bf64684539bc)

**Smartphone (please complete the following information):**
 - Device: [iPad 9]
 - OS: [iPadOS]
 - Version [17.6.1 (21G93)]

**Additional context**
I used the ipa from this url.
https://nightly.link/cranci1/Ryu/workflows/build/main/Ryu-IPA.zip

**Comment by cranci1** [comment]
ohhh yeah its a issue with the "custom" player, soon will be fixed. Thanks

**Comment by cranci1** [comment]
Issue has been fixed, Thanks!
