### ISSUE TITLE
 [FEATURE REQUEST] Add Russian extensions such as Anilibria 

### ISSUE THREAD

**Issue by zondaxxx** [cranci1/Ryu#17]
I’m Russian anime-lover, and I interested in your app. Can you add Russian Anilibria source. On GitHub they have an api docs repository

**Comment by cranci1** [comment]
what's the name of the API repo?

**Comment by zondaxxx** [comment]
https://github.com/anilibria/docs
it is on Russian, but you easily can use translator or smth else

It will be pretty amazing if you add anilibria support.

**Comment by cranci1** [comment]
ok so I started adding it as a source, the only small problem I'm currently facing is that they use torrents for streams, which may make this source not fully possible

**Comment by zondaxxx** [comment]
omg, that is very good news! thanks for ur suppoting my idea. I really hope that you will succeed

**Comment by zondaxxx** [comment]
I see that anime parsing from Anilist and if it possible can you add parsing from AniLibria servers to avoid bugs, and descriptions and covers loading on Russian?
I can help with localization and translate your sections on Russian.

Give me a list of keywords to translate

**Comment by cranci1** [comment]
Yes, all the info about the anime will be parsed using the AniLibria API, from anilist nothing will be parsed. This means that the description/titles will be in Russian.

For the localization you need to give a bit of time since i need to find a better way to create the translation file

**Comment by cranci1** [comment]
Well, good news, AniLibria has been successfully added to Ryu.

Right now downloads are not working because of the structure of their video files. (They have support for streams in HD, FHD, SHD, but I'll had selection of those soon)
