### ISSUE TITLE
[BUG] No feedback on episode click 

### ISSUE THREAD

**Issue by albertogasparin** [cranci1/Ryu#18]
**Describe the bug**
When I click on an episode to start watching, nothing happens for 5s or so. If I tap again, then the app might get confused and kinda double start watching an episode.
I have HiAnime as selected source, using the default player.

**To Reproduce**
1) set HiAnime as source
2) search for attack on titan
3) pick a serie
3) click on an episode
4) nothing happens for several seconds, then the episode starts playing 

**Expected behavior**
Maybe a spinner or the player shows up

**Smartphone (please complete the following information):**
 - Device: iPad 11 Pro
 - OS: iOS 18.0.1
 - Version: 112

**Comment by cranci1** [comment]
Thanks for the idea, i'll add something like a spinning alert.

**Comment by cranci1** [comment]
Ok this should be done, it will now show a loading alert on all sources when you you press an episode cell.

https://github.com/user-attachments/assets/d49f5641-6a41-4b51-b8d4-c7abefd7ec58
