### ISSUE TITLE
[FEATURE REQUEST] Adding anime sources

### ISSUE THREAD

**Issue by tagjg** [cranci1/Ryu#20]
**Is your feature request related to a problem? Please describe.**
Adding anime sources

**Describe the solution you'd like**
Add the URL https://aniplaynow.live/

I'd be happy if there was a function that could be implemented to add this.

As follows.

・Search supports Japanese, so there's no need to search for anime titles in English.

At least, this site https://aniplaynow.live/
can do this.

・You can also download.
At least, this site https://aniplaynow.live/
can do this.

・You can turn off subtitles.

At least, you can do it on this site: https://aniplaynow.live/

**Comment by cranci1** [comment]
I'll see if is possible to add it
