### ISSUE TITLE
[FEATURE REQUEST] Allow user to pick no subtitles as default

### ISSUE THREAD

**Issue by albertogasparin** [cranci1/Ryu#21]
**Is your feature request related to a problem? Please describe.**
I watch the episodes in dub and so don’t need subtitles. I currently have “always ask” setting enabled in order to pick “no subtitles” before an episode starts, but that is a bit annoying as it requires an extra interaction before playing.

**Describe the solution you'd like**
In the sources settings, add “No subtitles” as default subtitles language or add a new setting (like preferred subtitles) to set subtitles hidden by default. Alternatively, introduce a way to have different preferences for sub and dub content, but might be overkill)

**Comment by cranci1** [comment]
Sure I'll add "No Subtitles" as direct option in the settings

**Comment by cranci1** [comment]
Perfect, this has been added thanks! This will also roll out in a few days with the new update
