### ISSUE TITLE
[BUG] Continue watching item remains even after last episode is marked as finished 

### ISSUE THREAD

**Issue by albertogasparin** [cranci1/Ryu#22]
**Describe the bug**
This might be a small quality of life improvement, but I’ve noticed that after watching an entire season, the home still shows it under “continue watching”. 

**To Reproduce**
1) watch an entire season / series 
2) home still shows the series in “continue watching”
3) clicking it autoplays an already seen episode 

**Expected behavior**
It would be nice to hide it automatically, or at least mark it as completed and not autoplay an already watched episode 

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: latest
 - Version: 117

**Comment by cranci1** [comment]
Oh, it's probably because I've reduced the remaining time from 120s to 90s, I'll revert it to to 120s has it is more accurate then

**Comment by albertogasparin** [comment]
Right, I usually stop watching around 100s from the end, so that makes sense 👍

**Comment by cranci1** [comment]
I've fixed this, it will be working in around 4 days with the new build
