### ISSUE TITLE
[BUG] TestFlight shows Ryu as AnimeGen

### ISSUE THREAD

**Issue by albertogasparin** [cranci1/Ryu#23]
**Describe the bug**
Today I noticed that in TestFlight Ryu is now called AnimeGen, but seems like that is a different project of yours rather than a rename. So likely an accidental mistake 

**To Reproduce**
1) open TestFlight 
2) the project shows up as AnimeGen with Ryu app icon 

**Smartphone (please complete the following information):**
 - Version: 117

**Additional context**

**Comment by cranci1** [comment]
Yeah it's not possible, this is just because i dont have a newer mac and so i can't create a new app, so im forced to use the old animegen project testflight because i had an automatic build upload, but renaming is not something possible im pretty sure

**Comment by albertogasparin** [comment]
Oh, I see, all good then
