### ISSUE TITLE
discord

### ISSUE THREAD

**Issue by niuperw** [cranci1/Ryu#24]
can you renew the discord server link?

**Comment by cranci1** [comment]
From where? (in the app or on github)

**Comment by niuperw** [comment]
> From where? (in the app or on github)

in app i tried to enter but limk is expired

**Comment by cranci1** [comment]
Works for me but i'll add a new invite

**Comment by cranci1** [comment]
In the mean time if you need an invite here it is:

https://discord.gg/Nxp97u2G
