### ISSUE TITLE
[BUG] Default 360p in specific source

### ISSUE THREAD

**Issue by zero13722** [cranci1/Ryu#25]
**Describe the bug**
Video plays with 360p despite preferred quality was set to 1080p in preferences. (HiAnime only)

**To Reproduce**
1) Open any video and it plays with 360p, you have to set back to 1080p manually everytime when start/resume an episode.

**Expected behavior**
Video should start with 1080p by default.

**Additional context**
My settings:
[Quality]
Preferred Quality: 1080p
Numbers of Retries: 10 Tries
[HiAnime]
Preferred Audio: sub
Preferred Server: hd-1/hd-2 (checked both)
[Player]
Play in Browser: Off
Media Player: Default

Other sources works fine, restart app or switch network didn't help.

**Comment by cranci1** [comment]
Oh yeah, this has been reported to me this morning. It's now fixed thanks. It will be out in 2/3 days, sorry
