### ISSUE TITLE
[BUG] Tapping the Selected Source Closes the App

### ISSUE THREAD

**Issue by rakicha** [cranci1/Ryu#26]
**Describe the bug**
Tapping the Selected Source in the Home category closes the app.

**To Reproduce**
1) From Home screen, tap on the gear icon (settings) on the top right corner.
2) Tap the source on the Selected Source menu.

**Expected behavior**
A dropdown menu of selectable sources is expected to be shown.

**Screenshots**
![photo_2024-10-27](https://github.com/user-attachments/assets/83d8294f-519a-4a92-ba57-2e4ccdb8daa4)

**Smartphone**
 - Device: iPad 6th generation
 - OS: iPadOS 17.7
 - Version Release 1.0.5

**Additional context**
Bug might be similar to [issue #7 Switching Sources](https://github.com/cranci1/Ryu/issues/7).

**Comment by cranci1** [comment]
Please use the nightly.link ipa, that issue is now fixed here: https://nightly.link/cranci1/Ryu/workflows/build/main/Ryu-IPA.zip

**Comment by rakicha** [comment]
i can confirm that the issue is fixed in the nightly.link ipa, selecting the source is now working as how it should. thank you.
