### ISSUE TITLE
[BUG] aniworld source not working

### ISSUE THREAD

**Issue by Chengobengo** [cranci1/Ryu#28]
**Describe the bug**
Everytime i try to watch an episode on aniworld i get an error saying „error extracting Vidoza URL“

**Smartphone (please complete the following information):**
 - Device: Iphone 15 Pro
 - OS: IOS 18.1
![IMG_2003](https://github.com/user-attachments/assets/c908bcc4-64b1-4edc-a6c1-e7679603af1c)

**Comment by cranci1** [comment]
Yeah sorry, i still need to implement the other streaming providers so only Vidoza is currently supported

**Comment by cranci1** [comment]
Ok so this issue has been fixed adding support for VOE. A new testflight build is coming out today/tomorrow. Sorry
