### ISSUE TITLE
[BUG] thumbnail/art issue - Continue Watching

### ISSUE THREAD

**Issue by bachig26** [cranci1/Ryu#29]
**Describe the bug**
The thumbnail for the episodes watched aren't available in the Continue Watching.
I initially thought it is due to watching a episode from a different provider and switching a other makes this issue (which I saw in the AnimeGen v2.0.0 (114)) but with the recent TestFlight version, this happens to being with the same provider.

**To Reproduce**
1) Play any content
2) Return to Homepage to see the issue

**Expected behavior**
To show the thumbnail or the art of the episode.

**Screenshots**

![IMG_1260](https://github.com/user-attachments/assets/cce88a40-ab4c-4812-adf6-66fde9b73c01)
![IMG_1258](https://github.com/user-attachments/assets/504a26ca-ffea-41dc-971b-3675ea65edf5)

**Smartphone (please complete the following information):**
 - Device: iPhone SE3
 - OS: iOS 18.1
 - Version: AnimeGen v2.0.0 (118) - TestFlight version

**Comment by cranci1** [comment]
So unfortunately is not something fixable on my end. The thumbnails are fetched using an API. This api doesn't have thumbnails for most recents anime. This is the api url: "https://api.ani.zip/mappings?anilist_id=176311"

**Comment by bachig26** [comment]
> So unfortunately is not something fixable on my end. The thumbnails are fetched using an API. This api doesn't have thumbnails for most recents anime. This is the api url: "https://api.ani.zip/mappings?anilist_id=176311" for that anime

uh okay. got it. thanks...
