### ISSUE TITLE
[BUG] Loading/Buffer Indicator misalignment - Video Player

### ISSUE THREAD

**Issue by bachig26** [cranci1/Ryu#30]
**Describe the bug**
the buffer indicator isn't aligned to the center of the display.
i think this maybe the player isn't properly launched as soon the episode is clicked to watch.
or the pre-buffer system isn't properly implement in terms of the visual aspect.

**To Reproduce**
1) Open a episode
2) the misalignment bug can be seen at start (buffer page)

**Expected behavior**
to be in the center of the display to be fit with player.

**Screenshots**

https://github.com/user-attachments/assets/c8c953c2-e775-4518-b9c8-09c02e1d40bf

**Smartphone (please complete the following information):**
 - Device: iPhone SE3
 - OS: iOS 18.1
 - Version: AnimeGen v2.0.0 (118) - TestFlight version

**Comment by cranci1** [comment]
lol my bad

**Comment by cranci1** [comment]
Thanks, i've fixed this issue
