### ISSUE TITLE
[BUG] Subtitles do not work when AirPlaying

### ISSUE THREAD

**Issue by puppyonline** [cranci1/Ryu#31]
**Describe the bug**
When airplaying content, the subtitles do not seem to work. They are selectable on the Apple TV but they do not show anything.

**To Reproduce**
1) Using the TestFlight version of Ryu, find an anime with subtitles and play it. 
2) Airplay the show to an Apple TV, then use the ATV remote to select the subtitles option in the corner. 
3) Selecting any option does not show anything.

**Expected behavior**
Subtitles should be working on Airplay streams.

**Screenshots**
![IMG_4005](https://github.com/user-attachments/assets/3b7822a0-557d-452d-9129-699bd106589a)
![IMG_4006](https://github.com/user-attachments/assets/919355f9-3062-4735-98a8-76ed1cee89d5)
![IMG_4007](https://github.com/user-attachments/assets/b51770ac-8216-4946-bf4f-e159b212bb3b)

**Device (please complete the following information):**
 - Device: iPhone 15 Pro Max
 - OS: 18.1 (22B82)
 - Version: 1.0.6-3 Build 1 TestFlight

**Comment by cranci1** [comment]
Yeah this may be difficult since that the subtitles are added on top of the video and not in the video track

**Comment by powerdollkirby** [comment]
> Yeah this may be difficult since that the subtitles are added on top of the video and not in the video track

Other videos work

for example AirPlay a movie with subtitles in safari shows the subtitles on screen
