### ISSUE TITLE
[BUG] Italian subtitles despite english in settings

### ISSUE THREAD

**Issue by persson1589** [cranci1/Ryu#37]
**Describe the bug**
Tried to watch episode 9 of dandadan, italian subtitles despite english subtitles in settings 

**To Reproduce**
1) play episode 9 of dandadan. 

**Expected behavior**
English subs

**Screenshots**

**Device (please complete the following information):**
 - Device: iPad 9th gen
 - OS: latest IpadOS stable
 - Version [latest]

**Additional context**

**Comment by cranci1** [comment]
Did you change the source correctly? Click on the blue text in the top left of the home, that should show a menu whit all the sources available.

**Comment by persson1589** [comment]
Yeah, I did that but I don't think it actually changed. I tried to change again to American sources and it works now! Sorry to bother you.

Maybe if you set English as default subtitle in settings the English source should be automatically picked?

I appreciate your work and this app, it works the best imo with the latest episodes as well.
