### ISSUE TITLE
Default player not working

### ISSUE THREAD

**Issue by Cabowski92** [cranci1/Ryu#4]
The default player buffers then just does nothing. Only using vlc seems to work. Infuse just gets an error as well
![IMG_5270](https://github.com/user-attachments/assets/959ebcdd-5f7e-4760-98c6-278d6c0de6de)

**Comment by cranci1** [comment]
So, infuse has a know issue for gogoanime and jkanime. vlc and outplayer works on all sources.

For the default media player that buffers infinitely is kinda weird, mind sending like a video?

**Comment by cranci1** [comment]
Have you tried changing the Tries in the settings?

**Comment by Cabowski92** [comment]
https://github.com/user-attachments/assets/8c99f9d5-62bb-497c-824c-6274bb12f186

The default player seems to have a problem with gogoanime and not animeheaven

**Comment by cranci1** [comment]
Yes, even on the Discord server I'm having reports of GoGoAnime not working, i need to figure this out

**Comment by cranci1** [comment]
Yeah it has been fixed
