### ISSUE TITLE
[BUG] HiAnime's Source has disappeared.

### ISSUE THREAD

**Issue by ghost** [cranci1/Ryu#43]
**Describe the bug**
The source for HiAnime has disappeared.

**To Reproduce**
1) Install AnimeGen (Ryu) from TestFlight.
2) Change the Source.
3) I can't find the source of HiAnime.

**Expected behavior**
You will now be able to select the HiAnime source.

**Screenshots**
![IMG_1416](https://github.com/user-attachments/assets/f6b0262c-65a0-4a7a-bb12-19ef480cc9e5)

**Device (please complete the following information):**
 - Device: [iPad 9]
 - OS: [iOS18.0]
 - Version [Ryu 2.0.0(125)]

**Additional context**
Previously, you could select the HiAnime source.

**Comment by bshar1865** [comment]
Hello, Hianime has been removed in current build due to Hianime API having issues. It will be added back once their API is stable, Please join Ryu server to keep up to date with Ryu News.
