### ISSUE TITLE
Swipe bar doesn’t disappear 

### ISSUE THREAD

**Issue by Cabowski92** [cranci1/Ryu#5]
When using the default player for gogoanime the swipe bar doesn’t disappear. 
![IMG_5275](https://github.com/user-attachments/assets/753d1e0a-ab0d-41b6-88c2-4796ce932651)

**Comment by Cabowski92** [comment]
Right under the subtitles

**Comment by cranci1** [comment]
oh yeah its true, I'll see if i can fix it, Thanks

**Comment by cranci1** [comment]
This issue has been fixed. Thanks, A new hotfix should come out tomorrow

**Comment by Cabowski92** [comment]
Thanks for such a great app to finally watch anime on iOS

**Comment by cranci1** [comment]
Thank you for using it
