### ISSUE TITLE
Switching Sources

### ISSUE THREAD

**Issue by Listlessness** [cranci1/Ryu#7]
When I switch sources it always goes back to anime world so I can't watch in English

**Comment by cranci1** [comment]
is the anime in the favorites?

**Comment by cranci1** [comment]
If the anime is a favourite, it will always use the source where it was set as favorite. This mean that to watch anime in english you would need to re search with that source the anime.

**Comment by Listlessness** [comment]
Okay it's not in favorite

**Comment by Listlessness** [comment]
I added it and it didn't change anything could you add me on discord "competent" so I can send some photos

**Comment by cranci1** [comment]
I sent you a frind request, you can also join the discord server if you want:

https://discord.gg/jQPSdF3E

**Comment by rakicha** [comment]
I am having the same issue. Should I make another bug report or continue from here?

**Comment by cranci1** [comment]
create a new issue pleass
